//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define IDD_RENAMETAKEDLG               104
#define IDD_ITEMPANVOLDIALOG            105
#define IDD_REPEATPASTEDLG              106
#define IDD_SELECT_NTH_ITEMDLG          107
#define IDD_EXOCOM_PARDLG               108
#define IDD_ITEMVOLUME                  111
#define IDD_DISKSPACECALC               114
#define IDD_CSPVOC_CONF                 116
#define IDD_RENDITEMS                   118
#define IDD_SCALEITEMPOS                119
#define IDD_RANDTEMPOS                  120
#define IDD_GEN_ENV1                    122
#define IDD_TAKEMIXER                   124
#define IDD_REPOSITEMS                  125
#define IDD_TAKEFINDER                  126
#define IDD_ITEM_INSPECTOR              128
#define IDD_ITEMPOSREMAP                129
#define IDD_RUBBERBAND                  130
#define IDD_MEDIADLG                    133
#define IDD_MULMATCH                    134
#define IDD_MENU_EDITOR                 135
#define IDD_AUTORENAMETAKES             138
#define IDD_SCANPROGR                   139
#define IDD_SPREADITEMS                 142
#define IDD_RNMTRAX                     143
#define IDD_ITEMPROPINTERP              145
#define IDD_SWINGITEMPOS                146
#define IDD_CRTNEWTX                    148
#define IDD_TOGSELRAND                  150
#define IDD_RENAMEDLG666                151
#define IDD_GENERICQUERY1               152
#define IDC_BUTTON1                     1000
#define IDC_EDIT1                       1001
#define IDC_BUTTON2                     1001
#define IDC_EDIT5                       1002
#define IDC_FIT_A                       1003
#define IDC_FOT_A                       1004
#define IDC_STATIC2                     1005
#define IDC_RANDPROB                    1005
#define IDC_TVOL_NUDGE                  1006
#define IDC_FIT_B                       1008
#define IDC_FOT_B                       1009
#define IDC_THGT_B                      1011
#define ID_TAKEONLY                     1020
#define ID_TAKEANDSOURCE                1021
#define IDC_CHECK1                      1023
#define IDC_PANEDIT                     1024
#define IDC_VOLEDIT                     1025
#define IDC_NUMREPEDIT                  1029
#define IDC_NOTEVALUECOMBO              1030
#define IDC_EDIT2                       1032
#define IDC_EDIT3                       1033
#define IDC_EDIT4                       1034
#define IDC_IVOL_NUDGE                  1035
#define IDC_PNUDGE_B                    1036
#define IDC_COMBO1                      1040
#define IDC_COMBO2                      1041
#define IDC_RADIO1                      1043
#define IDC_RADIO2                      1044
#define IDC_RADIO3                      1045
#define IDC_FOS_A                       1047
#define IDC_FOS_B                       1048
#define IDC_FIS_A                       1049
#define IDC_FIS_B                       1050
#define IDC_EXTTOOL1BUT                 1051
#define IDC_EXTTOOL2BUT                 1052
#define IDC_EXTTOOLPATH1                1053
#define IDC_EXTTOOLPATH2                1054
#define IDC_EXTEDIT1BUT                 1055
#define IDC_EXTEDITPATH1                1056
#define IDC_EXTEDIT2BUT                 1057
#define IDC_STRIPCONTAINER              1058
#define IDC_EXTEDITPATH2                1058
#define IDC_APPLY                       1060
#define IDC_CHECK2                      1062
#define IDC_CHECK3                      1063
#define IDC_STATIC1                     1064
#define IDC_IISTATIC1                   1072
#define IDC_IPRCURVE                    1073
#define IDC_RBPEDIT2                    1074
#define IDC_RBPEDIT3                    1075
#define IDC_RBPEDIT1                    1076
#define IDC_EDITPIXAM                   1087
#define IDC_EDITCURSECS                 1088
#define IDC_PROJFOLMEDLIST              1089
#define IDC_PROJFILES_USED              1090
#define IDC_SHOWUNUS                    1091
#define IDC_FINDMISSING                 1092
#define IDC_MULMATCHLIST                1093
#define IDC_DELFILESBUT                 1094
#define ID_CLOSE                        1095
#define IDC_XENACTLIST                  1096
#define IDC_DELFILESBUT2                1096
#define IDC_MENUTOCONF                  1097
#define IDC_TAKENAME_EDIT               1111
#define IDC_FILENAME_EDIT               1112
#define IDC_FULLFILENAME                1113
#define IDC_RENAMEMEDIA                 1114
#define IDC_AUTONAMEOUTPUT              1115
#define IDC_SAMPLEOUT                   1116
#define IDC_AUTONAMEPRESETS             1117
#define IDC_HIDEPATHS                   1118
#define IDC_SCANFILE                    1119
#define IDC_COPYTOPROJFOL               1120
#define IDC_THGT_A                      1121
#define IDC_EDITTRSUFFIX                1122
#define IDC_EDITDEFAULTTRACKNAME        1123
#define IDC_EDITTRPREFIX                1124
#define IDC_STATIC7                     1125
#define IDC_IIENVAREA                   1127
#define IDC_IIACTPARLIST                1129
#define IDC_IIRESETENV                  1130
#define IDC_IIPLAYPROJ                  1131
#define IDC_IILOOPPROJ                  1132
#define IDC_COMPARSECTLOOP              1133
#define IDC_IIPRESETALL                 1135
#define IDC_ABORT                       1136
#define IDC_TKVOLNUDLAB                 1138
#define IDC_RANDMEAN                    1139
#define IDC_NUDGE_S                     1140
#define IDC_NUDGE_B                     1141
#define IDC_PNUDGE_A                    1142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1143
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
