---
language: cpp
os: osx
git:
  depth: false
env:
  - ARCH=x86_64
  - ARCH=i386
install:
  - curl -fsSL https://gist.github.com/cfillion/da355e8278048de08ae065d6fe6031c1/raw/reaper_plugin_functions.h -o vendor/reaper_plugin_functions.h
script:
  - mkdir build && cd build
  - cmake ..
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_OSX_ARCHITECTURES="$ARCH"
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.5
      -DNO_INSTALL_PREFIX=YES
  - cmake --build .
  - cpack

  - |-
    if [ "$TRAVIS_BRANCH" == "master" ] && [ -n "$DEPLOY_KEY" ]; then
      echo "$DEPLOY_KEY" | base64 -D > deploy_key && chmod 600 deploy_key &&
      scp -i deploy_key -o StrictHostKeyChecking=NO -q sws*.dmg \
        swsci@sws-extension.org:/var/www/standingwaterstudios.com/public_html/download/pre-release
    fi
addons:
  homebrew:
    packages:
      - cmake # must have version 3.15 or newer
    update: true
