//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sws_extension.rc
//
#define IDD_CONSOLE                     100
#define IDD_SNAPS                       101
#define IDD_MARKERLIST                  102
#define IDD_SAVE                        103
#define IDD_LOAD                        104
#define IDC_ZOOM_IN                     104
#define IDD_FORMAT                      105
#define IDD_MACRODEBUG                  106
#define IDD_COLOR                       107
#define IDD_TRACKLIST                   108
#define IDD_ABOUT                       109
#define IDD_PROMPT                      110
// unused                               111
#define IDD_SSMERGE                     112
#define IDD_INFO                        113
#define IDD_RECVMISSING                 114
#define IDD_AUTOCOLOR                   115
#define IDD_RENAMETAKEDLG               116
#define IDD_ITEMPANVOLDIALOG            117
#define IDD_REPEATPASTEDLG              118
#define IDD_SELECT_NTH_ITEMDLG          119
#define IDD_EXOCOM_PARDLG               120
#define IDD_ITEMVOLUME                  121
#define IDD_DISKSPACECALC               122
#define IDD_RENDITEMS                   124
#define IDD_SCALEITEMPOS                125
#define IDD_RANDTEMPOS                  126
#define IDD_TAKEMIXER                   128
#define IDD_REPOSITEMS                  129
#define IDD_TAKEFINDER                  130
#define IDD_ITEM_INSPECTOR              131
#define IDD_ITEMPOSREMAP                132
#define IDD_MEDIADLG                    134
#define IDD_MULMATCH                    135
#define IDD_AUTORENAMETAKES             136
#define IDD_SCANPROGR                   137
#define IDD_SPREADITEMS                 138
#define IDD_RNMTRAX                     139
#define IDD_ITEMPROPINTERP              140
#define IDD_SWINGITEMPOS                141
#define IDD_CRTNEWTX                    142
#define IDD_TOGSELRAND                  143
#define IDD_RENAMEDLG666                144
#define IDD_GENERICQUERY1               145
#define IDD_PROJLIST                    146
#define IDD_PADRELFO_GENERATOR          147
#define IDD_PADRE_ENVPROCESSOR          148
#define IDD_SNM_CUEBUSS                 149
#define IDD_SNM_RESOURCES               150
#define IDD_ZOOMPREFS                   151
#define IDD_SNM_NOTES                   152
#define IDC_ZOOM_OUT                    152
#define IDD_SNM_WAIT                    153
#define IDC_ZOOM_UNDO                   153
#define IDD_SNM_FIND                    154
#define IDD_SNM_LIVE_CONFIGS            155
#define IDD_AW_ITEM_SMOOTHING           156
#define IDD_GROOVEDIALOG                157
#define IDD_AUTORENDER_METADATA         158
#define IDD_RECINPUTCHECK               159
#define IDD_AUTORENDER_PREFERENCES      160
#define IDC_ZOOM_DRAG                   160
#define IDD_SNM_CYCLACTION              161
#define IDD_SNM_IMAGE                   162
#define IDD_IX_LABELDLG                 163
#define IDD_SNM_RGNPLAYLIST             165
#define IDD_BR_MARKERS_TO_TEMPO         166
#define IDD_BR_SELECT_ADJUST_TEMPO      167
#define IDD_BR_UNSELECT_TEMPO           168
#define IDD_SNM_LIVE_CONFIG_MON         169
#define IDD_BR_TEMPO_SHAPE_OPTIONS      170
#define IDD_BR_RANDOMIZE_TEMPO          171
#define IDD_BR_VERSION                  172
#define IDD_PROMPT_OPTION               173
#define IDD_BR_LOUDNESS_ANALYZER        174
#define IDD_BR_LOUDNESS_ANALYZER_NORM   175
#define IDD_BR_LOUDNESS_NORM_PROGRESS   176
#define IDD_BR_LOUDNESS_NORMALIZE       177
#define IDD_BR_TOOLTIP                  178
#define IDD_BR_LOUDNESS_PREF            179
#define IDD_BR_LOUDNESS_EXPORT_FORMAT   180
#define IDD_BR_CONTEXTUAL_TOOLBARS      181
#define IDD_BR_CONTEXTUAL_TOOLBARS_POS  182
#define IDD_BR_ADJUST_PLAYRATE          183
#define IDC_ENV_PEN_GRID                184
#define IDC_GRID_WARP                   185
#define IDC_ENV_PT_ADJ_VERT             186
#define IDC_MISC_SPEAKER                187
#define IDD_NF_LOUDNESS_ANALYZE_PROGRESS 188 // #880
#define IDC_ERASER                      189 // NF Eraser tool
#define IDB_UP                          500
#define IDB_DOWN                        501
#define IDC_BUTTON1                     1000
#define IDC_EDIT1                       1001
#define IDC_BUTTON2                     1002
#define IDC_EDIT5                       1003
#define IDC_FIT_A                       1004
#define IDC_FOT_A                       1005
#define IDC_STATIC2                     1006
#define IDC_RANDPROB                    1007
#define IDC_TVOL_NUDGE                  1008
#define IDC_FIT_B                       1009
#define IDC_FOT_B                       1010
#define IDC_THGT_B                      1011
#define ID_TAKEONLY                     1012
#define ID_TAKEANDSOURCE                1013
#define IDC_CHECK1                      1014
#define IDC_PANEDIT                     1015
#define IDC_ITEMZOOM                    1015
#define IDC_VOLEDIT                     1016
#define IDC_UNDOZOOM                    1016
#define IDC_NUMREPEDIT                  1017
#define IDC_MOVECUR                     1017
#define IDC_NOTEVALUECOMBO              1018
#define IDC_UNDOSWSONLY                 1018
#define IDC_EDIT2                       1019
#define IDC_LASTUNDOPROJ                1019
#define IDC_EDIT3                       1020
#define IDC_SETTIMESEL                  1020
#define IDC_SEEKPLAY                    1021
#define IDC_IVOL_NUDGE                  1022
#define IDC_DRAGUPPER                   1022
#define IDC_PNUDGE_B                    1023
#define IDC_DRAGLOWER                   1023
#define IDC_COMBO1                      1024
#define IDC_COMBO2                      1025
#define IDC_RADIO1                      1026
#define IDC_RADIO2                      1027
#define IDC_RADIO3                      1028
#define IDC_FOS_A                       1029
#define IDC_FOS_B                       1030
#define IDC_FIS_A                       1031
#define IDC_FIS_B                       1032
#define IDC_EXTTOOL1BUT                 1033
#define IDC_EXTTOOL2BUT                 1034
#define IDC_EXTTOOLPATH1                1035
#define IDC_EXTTOOLPATH2                1036
#define IDC_EXTEDIT1BUT                 1037
#define IDC_EXTEDITPATH1                1038
#define IDC_EXTEDIT2BUT                 1039
#define IDC_STRIPCONTAINER              1040
#define IDC_EXTEDITPATH2                1041
#define IDC_APPLY                       1042
#define IDC_CHECK2                      1043
#define IDC_CHECK3                      1044
#define IDC_STATIC1                     1045
#define IDC_IISTATIC1                   1046
#define IDC_IPRCURVE                    1047
#define IDC_EDITPIXAM                   1051
#define IDC_EDITCURSECS                 1052
#define IDC_PROJFOLMEDLIST              1053
#define IDC_PROJFILES_USED              1054
#define IDC_SHOWUNUS                    1055
#define IDC_FINDMISSING                 1056
#define IDC_MULMATCHLIST                1057
#define IDC_DELFILESBUT                 1058
#define ID_CLOSE                        1059
#define IDC_DELFILESBUT2                1060
#define IDC_TAKENAME_EDIT               1061
#define IDC_FILENAME_EDIT               1062
#define IDC_FULLFILENAME                1063
#define IDC_RENAMEMEDIA                 1064
#define IDC_AUTONAMEOUTPUT              1065
#define IDC_AUTONAMEPRESETS             1067
#define IDC_HIDEPATHS                   1068
#define IDC_SCANFILE                    1069
#define IDC_COPYTOPROJFOL               1070
#define IDC_THGT_A                      1071
#define IDC_EDITTRSUFFIX                1072
#define IDC_EDITDEFAULTTRACKNAME        1073
#define IDC_EDITTRPREFIX                1074
#define IDC_STATIC7                     1075
#define IDC_IIENVAREA                   1076
#define IDC_IIACTPARLIST                1077
#define IDC_IIRESETENV                  1078
#define IDC_IIPLAYPROJ                  1079
#define IDC_IILOOPPROJ                  1080
#define IDC_COMPARSECTLOOP              1081
#define IDC_IIPRESETALL                 1082
#define IDC_ABORT                       1083
#define IDC_TKVOLNUDLAB                 1084
#define IDC_RANDMEAN                    1085
#define IDC_NUDGE_S                     1086
#define IDC_NUDGE_B                     1087
#define IDC_PNUDGE_A                    1088
#define IDC_ADD                         1090
#define IDC_DELETE                      1091
#define IDC_PREVIEW                     1092
#define IDC_REMOVE                      1093
// unused                               1094
#define IDC_LIST                        1095
#define IDC_EDIT                        1096
#define IDC_COMBO                       1097
#define IDC_COMMAND                     1098
#define IDC_STATUS                      1099
#define IDC_SAVE                        1100
#define IDC_MUTE                        1101
#define IDC_SOLO                        1102
#define IDC_VOL                         1103
#define IDC_PAN                         1104
#define IDC_SENDS                       1105
#define IDC_HELPTEXT                    1106
#define IDC_UPDATE                      1107
#define IDC_SELECTEDONLY_RECALL         1108
#define IDC_VISIBILITY                  1109
#define IDC_SELECTION                   1110
#define IDC_OPTIONS                     1111
#define IDC_APPLYRECALL                 1112
#define IDC_FILTERGROUP                 1113
#define IDC_DESC                        1114
#define IDC_SHOWSELONLY                 1114
#define IDC_NAMEPROMPT                  1115
#define IDC_COLOR1                      1116
#define IDC_SELECTEDONLY_SAVE           1116
#define IDC_HIDENEW                     1117
#define IDC_COLOR2                      1118
#define IDC_FXCHAIN                     1119
#define IDC_SETCUST                     1120
#define IDC_SAVECOL                     1121
#define IDC_LOADCOL                     1122
#define IDC_LOADFROMTHEME               1123
#define IDC_VERSION                     1124
#define IDC_WEBSITE                     1125
#define IDC_FILTER                      1126
#define IDC_HIDE                        1128
#define IDC_CLEAR                       1129
#define IDC_STATIC_FILTER               1130
#define IDC_LINK                        1131
#define IDC_MIX                         1132
#define IDC_CURVIS                      1133
#define IDC_CUSTOM                      1134
#define IDC_INFO                        1135
#define IDC_AUTOCLOSE_INACTIVE          1136
#define IDC_FILES                       1137
#define IDC_NAME                        1138
#define IDC_SNAME                       1139
#define IDC_TRACK                       1140
#define IDC_TEXT                        1141
#define IDC_COLOR                       1147
#define IDC_PADRELFO_SYNCFREQUENCY      1148
#define IDC_PADRELFO_FREQUENCY          1149
#define IDC_PADRELFO_DELAY              1150
#define IDC_PADRELFO_SYNCDELAY          1151
#define IDC_PADRELFO_STRENGTH           1152
#define IDC_PADRELFO_OFFSET             1153
#define IDC_PADRELFO_LFOSHAPE           1154
#define IDC_PADRELFO_TAKEENV            1155
#define IDC_PADRELFO_MIDICC             1156
#define IDC_PADRELFO_TIMESEGMENT        1157
#define IDC_PADRELFO_TARGET             1158
#define IDC_PADRELFO_ACTIVETAKES        1159
#define IDC_PADREENVPROC_TYPE           1160
#define IDC_PADREENVPROC_OFFSET         1161
#define IDC_PADREENVPROC_STRENGTH       1162
#define IDC_SNM_CUEBUS_NAME             1163
#define IDC_SNM_CUEBUS_TYPE             1164
#define IDC_SNM_CUEBUS_SOLOGRP          1165
#define IDC_SNM_CUEBUS_HWOUT1           1166
#define IDC_SNM_CUEBUS_HWOUT2           1167
#define IDC_SNM_CUEBUS_HWOUT3           1168
#define IDC_SNM_CUEBUS_HWOUT4           1169
#define IDC_SNM_CUEBUS_HWOUT5           1170
#define IDC_SNM_CUEBUS_HWOUT6           1171
#define IDC_SNM_CUEBUS_HWOUT7           1172
#define IDC_SNM_CUEBUS_HWOUT8           1173
#define IDC_SNM_CUEBUS_TEMPLATE         1174
#define IDC_PLAY                        1175
#define IDC_SCROLL                      1177
#define IDC_PADREENVPROC_TARGET         1178
#define IDC_PADREENVPROC_ACTIVETAKES    1179
#define IDC_PADREENVPROC_TIMESEGMENT    1180
#define IDC_MMZOOM                      1180
#define IDC_PADREENVPROC_TAKEENV        1181
#define IDC_MMMODIFIER                  1181
#define IDC_CHECK4                      1182
#define IDC_DRAGUP_ZOOM                 1182
#define IDC_DRAGUP_UNZOOM               1183
#define IDC_DRAGUP_UNDO                 1184
#define IDC_TRIG_PAD                    1185
#define IDC_XFADE_LEN1                  1186
#define IDC_MAX_GAP                     1187
#define IDC_STRTCH_LIMIT                1188
#define IDC_TRANS_LEN                   1189
#define IDC_XFADE_LEN2                  1190
#define IDC_FADE_SHAPE                  1191
#define IDC_SLIDER1                     1192
#define IDC_SLIDER2                     1193
#define IDC_APPLYGROOVE                 1194
#define IDC_GROOVELIST                  1195
#define IDC_SENS_4TH                    1196
#define IDC_SENS_8TH                    1197
#define IDC_SENS_16TH                   1198
#define IDC_SENS_32ND                   1199
#define IDC_STRENGTH                    1200
#define IDC_SENS_GROUP                  1201
#define IDC_TARG_GROUP                  1202
#define IDC_TARG_ITEMS                  1203
#define IDC_TARG_NOTES                  1204
#define IDC_STORE                       1205
#define IDC_VELSTRENGTH                 1206
#define IDC_STRENGTH_GROUP              1207
#define IDC_ARTIST                      1208
#define IDC_ALBUM                       1209
#define IDC_GENRE                       1210
#define IDC_YEAR                        1211
#define IDC_COMMENT                     1212
#define IDC_RENDER_PATH                 1213
#define IDC_BROWSE                      1214
#define IDC_DONTSHOW                    1215
#define IDC_DEFAULT_RENDER_PATH         1221
#define IDC_STATIC_ARTIST               1224
#define IDC_STATIC_ALBUM                1225
#define IDC_STATIC_GENRE                1226
#define IDC_STATIC_YEAR                 1227
#define IDC_STATIC_COMMENT              1228
#define IDC_DRAGSCALE                   1230
#define IDC_LIST1                       1231
#define IDC_LIST2                       1232
#define IDC_PROGRESS                    1234
#define IDC_GROUP1                      1236
#define IDC_GROUP2                      1237
#define IDC_GROUP3                      1238
#define IDC_GROUP4                      1239
#define IDC_BR_CON_NUM                  1240
#define IDC_BR_CON_DEN                  1241
#define IDC_BR_CON_MARKERS              1242
#define IDC_BR_CON_TIMESEL              1243
#define IDC_BR_CON_REMOVE               1244
#define IDC_BR_SEL_BPM_END              1245
#define IDC_BR_SEL_BPM_START            1246
#define IDC_BR_ADJ_BPM_VAL              1247
#define IDC_BR_SEL_SHAPE                1248
#define IDC_BR_SEL_TYPE                 1249
#define IDC_BR_SEL_GROUP                1250
#define IDC_BR_ADJ_GROUP                1251
#define IDC_BR_ADJ_BPM_TAR_1            1252
#define IDC_BR_SEL_SIG_NUM              1253
#define IDC_BR_SEL_SIG_DEN              1254
#define IDC_BR_SEL_BPM                  1255
#define IDC_BR_SEL_SIG                  1256
#define IDC_BR_SEL_TIME_RANGE           1257
#define IDC_BR_SEL_ADD                  1258
#define IDC_BR_SEL_SELECT               1259
#define IDC_BR_SEL_INVERT               1260
#define IDC_BR_SEL_CLEAR                1261
#define IDC_BR_ADJ_SHAPE                1262
#define IDC_BR_ADJ_BPM_CUR_1            1263
#define IDC_BR_ADJ_BPM_PERC             1264
#define IDC_BR_ADJ_BPM_CUR_3            1265
#define IDC_BR_ADJ_BPM_TAR_3            1266
#define IDC_BR_ADJ_BPM_CUR_2            1267
#define IDC_BR_ADJ_BPM_TAR_2            1268
#define IDC_BR_ADJ_APPLY                1269
#define IDC_BR_ADJ_BPM_VAL_ENB          1270
#define IDC_BR_ADJ_BPM_PERC_ENB         1271
#define IDC_BR_SEL_INVERT_PREF          1272
#define IDC_BR_SEL_UNSELECT             1273
#define IDC_BR_SEL_UNSELECT_NTH         1274
#define IDC_BR_UNSEL_NTH_TEMPO          1275
#define IDC_BR_UNSEL_CRITERIA           1276
#define IDC_BR_CON_GRADUAL              1277
#define IDC_BR_CON_SPLIT_RATIO          1278
#define IDC_BR_CON_SPLIT                1279
#define IDC_BR_CON_GROUP2               1280
#define IDC_BR_SHAPE_SPLIT              1281
#define IDC_BR_SHAPE_SPLIT_RATIO        1282
#define IDC_BR_RAND_MIN                 1283
#define IDC_BR_RAND_MAX                 1284
#define IDC_BR_RAND_UNIT                1285
#define IDC_BR_RAND_LIMIT_MIN           1286
#define IDC_BR_RAND_LIMIT_MAX           1287
#define IDC_BR_RAND_LIMIT_UNIT          1288
#define IDC_BR_RAND_LIMIT               1289
#define IDC_BR_RAND_SEED                1290
#define IDC_BR_SEL_BPM_STATIC           1291
#define IDC_BR_SEL_SIG_STATIC           1292
#define IDC_BR_CON_MARKERS_STATIC       1293
#define IDC_BR_CON_SIG_STATIC1          1294
#define IDC_BR_CON_SIG_STATIC2          1295
#define IDC_BR_VER_MESSAGE              1296
#define IDC_BR_VER_PROGRESS             1297
#define IDC_BR_VER_OFF                  1298
#define IDC_BR_VER_BETA                 1299
#define IDC_BR_VER_DOWNLOAD             1300
#define IDC_PREVIOUS                    1301
#define IDC_NEXT                        1302
#define IDC_SWAP_UP                     1303
#define IDC_SWAP_DOWN                   1304
#define IDC_ANALYZE                     1305
#define IDC_CANCEL                      1306
#define IDC_MIN                         1307
#define IDC_MAX                         1308
#define IDC_PROJ_LU                     1309
#define IDC_GLOBAL_LU                   1310
#define IDC_ENB_PROJ_LU                 1311
#define IDC_LU_FORMAT                   1312
#define IDC_TARGET                      1313
#define IDC_ENB_PROJ_GRAPH              1314
#define IDC_UNIT                        1315
#define IDC_VALUE                       1316
#define IDC_MIN_PROJ                    1317
#define IDC_MAX_PROJ                    1318
#define IDC_WILDCARDS                   1319
#define IDC_FORMAT                      1320
#define IDC_FORMAT_STATIC               1321
#define IDC_PREVIEW_STATIC              1322
#define IDC_PRESET                      1323
#define IDC_ALL_BOX                     1324
#define IDC_ALL_FOCUS                   1325
#define IDC_ALL_FOCUS_COMBO             1326
#define IDC_ALL_TOPMOST                 1327
#define IDC_TCP_BOX                     1328
#define IDC_TCP_TRACK                   1329
#define IDC_TCP_TRACK_COMBO             1330
#define IDC_TCP_ENV                     1331
#define IDC_TCP_ENV_COMBO               1332
#define IDC_MCP_BOX                     1333
#define IDC_MCP_TRACK                   1334
#define IDC_MCP_TRACK_COMBO             1335
#define IDC_ARG_BOX                     1336
#define IDC_ARG_TRACK                   1337
#define IDC_ARG_TRACK_COMBO             1338
#define IDC_ARG_ITEM                    1339
#define IDC_ARG_ITEM_COMBO              1340
#define IDC_ARG_TRACK_ENV               1341
#define IDC_ARG_TRACK_ENV_COMBO         1342
#define IDC_ARG_TAKE_ENV                1343
#define IDC_ARG_TAKE_ENV_COMBO          1344
#define IDC_ARG_TAKE_ACTIVATE           1345
#define IDC_MIDI_BOX                    1346
#define IDC_MIDI_CC_LANE_CLICKED        1347
#define IDC_INLINE_BOX                  1348
#define IDC_INLINE_ITEM                 1349
#define IDC_INLINE_ITEM_COMBO           1350
#define IDC_INLINE_CC_LANE_CLICKED      1351
#define IDC_HELP_WIKI                   1352
#define IDC_ARG_STRETCH                 1353
#define IDC_ARG_STRETCH_COMBO           1354
#define IDC_ALL_POS                     1355
#define IDC_ALL_POS_H_COMBO             1356
#define IDC_ALL_POS_V_COMBO             1357
#define IDC_ALL_FOREGROUND              1358
#define IDC_DELTRACKSPROMPT             1359 // snapshots
#define IDC_PHASE                       1360 // snapshots
#define IDC_PLAY_OFFSET                 1361 // snapshots

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         40000
#define _APS_NEXT_CONTROL_VALUE         1362
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
