//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sws_extension.rc
//
#define IDD_CONSOLE                     100
#define IDD_SNAPS                       101
#define IDD_MARKERLIST                  102
#define IDD_SAVE                        103
#define IDD_LOAD                        104
#define IDD_FORMAT                      105
#define IDD_MACRODEBUG                  106
#define IDD_COLOR                       107
#define IDD_TRACKLIST                   108
#define IDD_ABOUT                       109
#define IDD_PROMPT                      110
#define IDD_MEDIAPOOL                   111
#define IDD_SSMERGE                     112
#define IDD_INFO                        113
#define IDD_RECVMISSING                 114
#define IDD_AUTOCOLOR                   115
#define IDD_RENAMETAKEDLG               116
#define IDD_ITEMPANVOLDIALOG            117
#define IDD_REPEATPASTEDLG              118
#define IDD_SELECT_NTH_ITEMDLG          119
#define IDD_EXOCOM_PARDLG               120
#define IDD_ITEMVOLUME                  121
#define IDD_DISKSPACECALC               122
#define IDD_CSPVOC_CONF                 123
#define IDD_RENDITEMS                   124
#define IDD_SCALEITEMPOS                125
#define IDD_RANDTEMPOS                  126
#define IDD_GEN_ENV1                    127
#define IDD_TAKEMIXER                   128
#define IDD_REPOSITEMS                  129
#define IDD_TAKEFINDER                  130
#define IDD_ITEM_INSPECTOR              131
#define IDD_ITEMPOSREMAP                132
#define IDD_RUBBERBAND                  133
#define IDD_MEDIADLG                    134
#define IDD_MULMATCH                    135
#define IDD_AUTORENAMETAKES             136
#define IDD_SCANPROGR                   137
#define IDD_SPREADITEMS                 138
#define IDD_RNMTRAX                     139
#define IDD_ITEMPROPINTERP              140
#define IDD_SWINGITEMPOS                141
#define IDD_CRTNEWTX                    142
#define IDD_TOGSELRAND                  143
#define IDD_RENAMEDLG666                144
#define IDD_GENERICQUERY1               145
#define IDD_PROJLIST                    146
#define IDD_PADRELFO_GENERATOR	        147

#define IDB_UP                          500
#define IDB_DOWN                        501
#define IDC_BUTTON1                     1000
#define IDC_EDIT1                       1001
#define IDC_BUTTON2                     1002
#define IDC_EDIT5                       1003
#define IDC_FIT_A                       1004
#define IDC_FOT_A                       1005
#define IDC_STATIC2                     1006
#define IDC_RANDPROB                    1007
#define IDC_TVOL_NUDGE                  1008
#define IDC_FIT_B                       1009
#define IDC_FOT_B                       1010
#define IDC_THGT_B                      1011
#define ID_TAKEONLY                     1012
#define ID_TAKEANDSOURCE                1013
#define IDC_CHECK1                      1014
#define IDC_PANEDIT                     1015
#define IDC_VOLEDIT                     1016
#define IDC_NUMREPEDIT                  1017
#define IDC_NOTEVALUECOMBO              1018
#define IDC_EDIT2                       1019
#define IDC_EDIT3                       1020
#define IDC_EDIT4                       1021
#define IDC_IVOL_NUDGE                  1022
#define IDC_PNUDGE_B                    1023
#define IDC_COMBO1                      1024
#define IDC_COMBO2                      1025
#define IDC_RADIO1                      1026
#define IDC_RADIO2                      1027
#define IDC_RADIO3                      1028
#define IDC_FOS_A                       1029
#define IDC_FOS_B                       1030
#define IDC_FIS_A                       1031
#define IDC_FIS_B                       1032
#define IDC_EXTTOOL1BUT                 1033
#define IDC_EXTTOOL2BUT                 1034
#define IDC_EXTTOOLPATH1                1035
#define IDC_EXTTOOLPATH2                1036
#define IDC_EXTEDIT1BUT                 1037
#define IDC_EXTEDITPATH1                1038
#define IDC_EXTEDIT2BUT                 1039
#define IDC_STRIPCONTAINER              1040
#define IDC_EXTEDITPATH2                1041
#define IDC_APPLY                       1042
#define IDC_CHECK2                      1043
#define IDC_CHECK3                      1044
#define IDC_STATIC1                     1045
#define IDC_IISTATIC1                   1046
#define IDC_IPRCURVE                    1047
#define IDC_RBPEDIT2                    1048
#define IDC_RBPEDIT3                    1049
#define IDC_RBPEDIT1                    1050
#define IDC_EDITPIXAM                   1051
#define IDC_EDITCURSECS                 1052
#define IDC_PROJFOLMEDLIST              1053
#define IDC_PROJFILES_USED              1054
#define IDC_SHOWUNUS                    1055
#define IDC_FINDMISSING                 1056
#define IDC_MULMATCHLIST                1057
#define IDC_DELFILESBUT                 1058
#define ID_CLOSE                        1059
#define IDC_DELFILESBUT2                1060
#define IDC_TAKENAME_EDIT               1061
#define IDC_FILENAME_EDIT               1062
#define IDC_FULLFILENAME                1063
#define IDC_RENAMEMEDIA                 1064
#define IDC_AUTONAMEOUTPUT              1065
#define IDC_SAMPLEOUT                   1066
#define IDC_AUTONAMEPRESETS             1067
#define IDC_HIDEPATHS                   1068
#define IDC_SCANFILE                    1069
#define IDC_COPYTOPROJFOL               1070
#define IDC_THGT_A                      1071
#define IDC_EDITTRSUFFIX                1072
#define IDC_EDITDEFAULTTRACKNAME        1073
#define IDC_EDITTRPREFIX                1074
#define IDC_STATIC7                     1075
#define IDC_IIENVAREA                   1076
#define IDC_IIACTPARLIST                1077
#define IDC_IIRESETENV                  1078
#define IDC_IIPLAYPROJ                  1079
#define IDC_IILOOPPROJ                  1080
#define IDC_COMPARSECTLOOP              1081
#define IDC_IIPRESETALL                 1082
#define IDC_ABORT                       1083
#define IDC_TKVOLNUDLAB                 1084
#define IDC_RANDMEAN                    1085
#define IDC_NUDGE_S                     1086
#define IDC_NUDGE_B                     1087
#define IDC_PNUDGE_A                    1088
#define IDC_LICENSE                     1089
#define IDC_ADD                         1090
#define IDC_DELETE                      1091
#define IDC_PREVIEW                     1092
#define IDC_REMOVE                      1093
#define IDC_ADDGROUP                    1094
#define IDC_LIST                        1095
#define IDC_EDIT                        1096
#define IDC_COMBO                       1097
#define IDC_COMMAND                     1098
#define IDC_STATUS                      1099
#define IDC_SAVE                        1100
#define IDC_MUTE                        1101
#define IDC_SOLO                        1102
#define IDC_VOL                         1103
#define IDC_PAN                         1104
#define IDC_SENDS                       1105
#define IDC_HELPTEXT                    1106
#define IDC_UPDATE                      1107
#define IDC_SELECTEDONLY                1108
#define IDC_VISIBILITY                  1109
#define IDC_SELECTION                   1110
#define IDC_OPTIONS                     1111
#define IDC_APPLYRECALL                 1112
#define IDC_FILTERGROUP                 1113
#define IDC_DESC                        1114
#define IDC_NAMEPROMPT                  1115
#define IDC_COLOR1                      1116
#define IDC_HIDENEW                     1117
#define IDC_COLOR2                      1118
#define IDC_FXCHAIN                     1119
#define IDC_SETCUST                     1120
#define IDC_SAVECOL                     1121
#define IDC_LOADCOL                     1122
#define IDC_LOADFROMTHEME               1123
#define IDC_VERSION                     1124
#define IDC_WEBSITE                     1125
#define IDC_FILTER                      1126
#define IDC_LATESTVER                   1127
#define IDC_HIDE                        1128
#define IDC_CLEAR                       1129
#define IDC_STATIC_FILTER               1130
#define IDC_LINK                        1131
#define IDC_MIX                         1132
#define IDC_CURVIS                      1133
#define IDC_CUSTOM                      1134
#define IDC_INFO                        1135
#define IDC_GROUPS                      1136
#define IDC_FILES                       1137
#define IDC_NAME                        1138
#define IDC_SNAME                       1139
#define IDC_TRACK                       1140
#define IDC_TEXT                        1141
#define IDC_ENABLED                     1142
#define IDC_COLOR                       1147
#define IDC_PADRELFO_SYNCFREQUENCY      1148
#define IDC_PADRELFO_FREQUENCY          1149
#define IDC_PADRELFO_DELAY              1150
#define IDC_PADRELFO_SYNCDELAY          1151
#define IDC_PADRELFO_STRENGTH           1152
#define IDC_PADRELFO_OFFSET             1153
#define IDC_PADRELFO_LFOSHAPE           1154
#define IDC_PADRELFO_TAKEENV            1155
#define IDC_PADRELFO_MIDICC             1156

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40000
#define _APS_NEXT_CONTROL_VALUE         1157
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
