set(CMAKE_SYSTEM_PROCESSOR armv7l)
set(TOOLCHAIN_PREFIX arm-linux-gnueabihf)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})
set(CMAKE_LIBRARY_PATH /usr/lib/${TOOLCHAIN_PREFIX})
set(CMAKE_INCLUDE_PATH /usr/include/${TOOLCHAIN_PREFIX})
set(ENV{PKG_CONFIG_PATH} /usr/lib/${TOOLCHAIN_PREFIX}/pkgconfig)
